# Generated by Django 4.0 on 2021-12-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='valid_from',
            field=models.DateTimeField(default=21),
            preserve_default=False,
        ),
    ]
